### ISSUE TITLE
Color Scheme

### ISSUE THREAD

**Issue by Nefrin** [FSIN-ohm/Matomat-Frontend#3]
Is there a set of colors that should be used? 

like a combination of 
![#2F9B92](https://placehold.it/15/2F9B92/000000?text=+) `Informatik Green`
![#0046A0](https://placehold.it/15/0046A0/000000?text=+) `Ohm Blue`
![#94ccc7](https://placehold.it/15/94ccc7/000000?text=+) ![#72a6e5](https://placehold.it/15/72a6e5/000000?text=+) `Light versions of these`
![#F5F5F5](https://placehold.it/15/F5F5F5/000000?text=+) `And some light gray`?

**Comment by theScrabi** [comment]
👍 I would love to have some kini orange in it as well, to highlight important things like "buy" or "purchase" button.
